from enum import StrEnum


class Role(StrEnum):
    RESIDENT = "RESIDENT"
    CUSTOMER_SERVICE = "CUSTOMER_SERVICE"
    REPAIR_WORKER = "REPAIR_WORKER"
    SECURITY_STAFF = "SECURITY_STAFF"
    FINANCE_STAFF = "FINANCE_STAFF"
    MANAGER = "MANAGER"
