"""
Canonical parameter hashing — the single hash algorithm for the whole system.

PRD 5.3 (PF-04) requires that a confirmation token generated by
``POST /api/confirmations`` can be consumed by any business module, and that
an idempotency key replay is detected with the exact same request hash.

That is only possible if *every* module derives ``parameter_hash`` /
``request_hash`` from one deterministic algorithm. Historically the platform,
repair and inspection modules each had their own variant, which silently made
cross-module confirmation impossible. This module is now the only
implementation; the others delegate to it.

Normalisation rules (applied recursively before serialisation):

* ``Enum``      → ``.value``            (so ``Urgency.NORMAL`` == ``"NORMAL"``)
* ``UUID``      → ``str(uuid)``         (so a parsed UUID == its JSON string)
* ``datetime``  → ``.isoformat()``
* ``Decimal``   → ``str(decimal)``      (never float — no precision loss)
* ``tuple`` / ``frozenset`` / ``set`` → sorted-stable ``list``
* ``dict``      → key-sorted ``dict``

Serialisation is ``json.dumps(..., sort_keys=True, separators=(",", ":"),
ensure_ascii=False)`` followed by SHA-256 hex digest.
"""
from __future__ import annotations

import hashlib
import json
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any
from uuid import UUID

__all__ = ["canonical_hash", "canonical_payload"]


def canonical_payload(value: Any) -> Any:
    """Recursively normalise a value into a JSON-serialisable canonical form."""
    if isinstance(value, Enum):
        return canonical_payload(value.value)
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime | date):
        return value.isoformat()
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, dict):
        return {str(key): canonical_payload(item) for key, item in sorted(value.items())}
    if isinstance(value, frozenset | set):
        return sorted(canonical_payload(item) for item in value)
    if isinstance(value, list | tuple):
        return [canonical_payload(item) for item in value]
    return value


def canonical_hash(value: Any) -> str:
    """Return the deterministic SHA-256 hex digest of ``value``.

    The same logical payload always yields the same digest regardless of
    whether it arrives as a parsed dataclass (``UUID``/``Enum`` objects) or as
    raw JSON from the client (plain strings).
    """
    payload = json.dumps(
        canonical_payload(value),
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()
