from property_agent.platform.roles import Role

TASK_READ_ROLES = (Role.MANAGER, Role.SECURITY_STAFF)
TASK_CREATE_ROLES = (Role.MANAGER, Role.SECURITY_STAFF)
TASK_ASSIGN_ROLES = (Role.MANAGER,)
TASK_COMPLETE_ROLES = (Role.MANAGER,)
TASK_ASSIGNEE_ROLES = (Role.SECURITY_STAFF,)

EVENT_READ_ROLES = (
    Role.MANAGER,
    Role.SECURITY_STAFF,
    Role.CUSTOMER_SERVICE,
    Role.RESIDENT,
)
EVENT_CREATE_ROLES = (
    Role.RESIDENT,
    Role.CUSTOMER_SERVICE,
    Role.SECURITY_STAFF,
    Role.MANAGER,
)
EVENT_ASSIGN_ROLES = (Role.MANAGER,)
EVENT_HANDLER_ROLES = (Role.SECURITY_STAFF,)
EVENT_REVIEW_ROLES = (Role.MANAGER,)
